wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/ROAR_PY_RL/training/train_online.py
    python_version: 3.8.19
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722117032
    t:
      1:
      - 1
      - 55
      - 105
      3:
      - 13
      - 23
      - 35
      4: 3.8.19
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
